name: lockscreen_calendar
description: A LockScreen Calendar
version: 0.0.1
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  bloc: ^8.0.2
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_localizations:
    sdk: flutter
  flutter_spinkit: ^5.1.0
  fluttertoast: ^8.0.9
  intl: ^0.17.0
  lottie: ^1.4.1
  platform_helper:
    path: packages/platform_helper

dev_dependencies:
  bloc_test: ^9.0.2
  flutter_test:
    sdk: flutter

  mocktail: ^0.3.0
  very_good_analysis: ^2.4.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/lottie/

flutter_gen:
  line_length: 80